# Generated by Django 2.2 on 2020-01-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_n_guesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='points',
        ),
    ]
