# Generated by Django 2.2 on 2020-01-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finished',
        ),
    ]
